export const GET_DOGS = 'GET_DOGS';
export const GET_DOGSBYNAME = 'GET_DOGSBYNAME';
export const SET_ORDER = 'SET_ORDER';
export const FILTER_TEMPERAMENT = 'FILTER_TEMPERAMENT';
export const FILTER_ORIGIN = 'FILTER_ORIGIN';
export const GET_TEMPERAMENTS = 'GET_TEMPERAMENTS';